# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install Flask Flask-SQLAlchemy Flask-Bcrypt Flask-Login

      # - name: Run Flask app
      #   env:
      #     FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
      #   run: |
      #     export FLASK_APP=app.py
      #     flask run --host=0.0.0.0
